//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmEnergo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OmEnergo.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О компании.
        /// </summary>
        public static string AboutCompany {
            get {
                return ResourceManager.GetString("AboutCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действия.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Административная панель.
        /// </summary>
        public static string AdministrativePanel {
            get {
                return ResourceManager.GetString("AdministrativePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл с таким именем уже загружен.
        /// </summary>
        public static string AFileWithThisNameHasAlreadyBeenUploaded {
            get {
                return ResourceManager.GetString("AFileWithThisNameHasAlreadyBeenUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены? Удаление элемента может привести к удалению всех связанных с ним элементов..
        /// </summary>
        public static string AreYouSure_OnDeleting {
            get {
                return ResourceManager.GetString("AreYouSure_OnDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аккуратно! Удаление или переименование свойств повлечёт удаление соответствующих свойств у продуктов и моделей!.
        /// </summary>
        public static string BeCareful_OnDeleting {
            get {
                return ResourceManager.GetString("BeCareful_OnDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каталог.
        /// </summary>
        public static string Catalog {
            get {
                return ResourceManager.GetString("Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить конфигурацию.
        /// </summary>
        public static string ChangeConfiguration {
            get {
                return ResourceManager.GetString("ChangeConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить содержимое сайта.
        /// </summary>
        public static string ChangeSiteContent {
            get {
                return ResourceManager.GetString("ChangeSiteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать файл.
        /// </summary>
        public static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компания ООО «ОмЭнерго» была образована в 2016 г. Основным направлением деятельности компании является обеспечение потребителей электротехнической продукцией высокого качества.
        ///
        ///В компании работают специалисты высокого уровня, способные проконсультировать своих клиентов по широкому спектру вопросов, связанных с техническими характеристиками поставляемой продукцией, ее монтажом, эксплуатацией и обслуживанием.
        ///
        ///Наша компания является официальным представителем ЭТК &quot;Энергия&quot; (РФ) на территории Республики Б [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CompanyDescription {
            get {
                return ResourceManager.GetString("CompanyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конфигурация.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Юридический и почтовый адрес:
        ///220055, РБ, г.Минск, ул.Каменногорская, д.47, оф.12 (2 этаж)
        ///Тел/факс: (+375-17) 248-77-45
        ///Velcom:  (+375-29) 341-31-35
        ///МТС: (+375-29) 560-01-79
        ///E-mail: info@omenergo.by.
        /// </summary>
        public static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакты.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заранее согласовывайте время приезда к нам!.
        /// </summary>
        public static string CoordinateTimeOfArrival {
            get {
                return ResourceManager.GetString("CoordinateTimeOfArrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать подсекцию.
        /// </summary>
        public static string CreateSubsection {
            get {
                return ResourceManager.GetString("CreateSubsection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные были успешно обновлены.
        /// </summary>
        public static string DataWasSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("DataWasSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Точно удалить.
        /// </summary>
        public static string DeleteExactly {
            get {
                return ResourceManager.GetString("DeleteExactly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доставка.
        /// </summary>
        public static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы осуществляем доставку продукции по всей стране. Доставка осуществляется собственным автотранспортом компании или с помощью транспортной компании ООО &quot;Автолайтэкспресс&quot;.
        ///
        ///По Минску доставка осуществляется БЕСПЛАТНО при покупке товара на общую сумму 170 рублей с НДС и более.
        ///При покупке товара до 170 рублей с НДС стоимость доставки - 6 рублей. Срок доставки – до 1 дня.
        ///
        ///По Беларуси доставка осуществляется БЕСПЛАТНО при покупке товара на общую сумму 250 рублей с НДС и более. При покупке товара до 250 р [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DeliveryDescription {
            get {
                return ResourceManager.GetString("DeliveryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скачать файл Excel.
        /// </summary>
        public static string DownloadExcelFile {
            get {
                return ResourceManager.GetString("DownloadExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электротехническая компания.
        /// </summary>
        public static string ElectricalCompany {
            get {
                return ResourceManager.GetString("ElectricalCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для того, чтобы отправление писем на почту gmail проходило успешно,
        ///необходимо в настройках аккаунта дать доступ сторонним приложениям.
        ///Сделать это можно по .
        /// </summary>
        public static string EmailConfigurationDescription_Beginning {
            get {
                return ResourceManager.GetString("EmailConfigurationDescription_Beginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to этой ссылке..
        /// </summary>
        public static string EmailConfigurationDescription_Ending {
            get {
                return ResourceManager.GetString("EmailConfigurationDescription_Ending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение посчитается автоматически, если сделать его пустым.
        /// </summary>
        public static string EnglishNamePropertyRecommendations {
            get {
                return ResourceManager.GetString("EnglishNamePropertyRecommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string Entrance {
            get {
                return ResourceManager.GetString("Entrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извините, во время обработки Вашего запроса произошла ошибка..
        /// </summary>
        public static string ErrorApologies {
            get {
                return ResourceManager.GetString("ErrorApologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратная связь.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя: {{name}}
        ///Телефон: {{phoneNumber}}
        ///Email: {{email}}
        ///Сообщение: {{text}}.
        /// </summary>
        public static string FeedbackEmailBody {
            get {
                return ResourceManager.GetString("FeedbackEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратная связь с сайта omenergo.by.
        /// </summary>
        public static string FeedbackFromTheOmenergoBySite {
            get {
                return ResourceManager.GetString("FeedbackFromTheOmenergoBySite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл менеджер.
        /// </summary>
        public static string FileManager {
            get {
                return ResourceManager.GetString("FileManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Миниатюры картинок.
        /// </summary>
        public static string ImagesThumbnails {
            get {
                return ResourceManager.GetString("ImagesThumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Миниатюры изображений были успешно созданы.
        /// </summary>
        public static string ImageThumbnailsWereSuccessfullyCreated {
            get {
                return ResourceManager.GetString("ImageThumbnailsWereSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка и выгрузка данных из Excel.
        /// </summary>
        public static string LoadingAndUnloadingDataFromExcel {
            get {
                return ResourceManager.GetString("LoadingAndUnloadingDataFromExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смотреть.
        /// </summary>
        public static string Look {
            get {
                return ResourceManager.GetString("Look", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная страница.
        /// </summary>
        public static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главные секции.
        /// </summary>
        public static string MainSections {
            get {
                return ResourceManager.GetString("MainSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сделать главным.
        /// </summary>
        public static string MakeItMain {
            get {
                return ResourceManager.GetString("MakeItMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метатег Description.
        /// </summary>
        public static string MetatagDescription {
            get {
                return ResourceManager.GetString("MetatagDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина метатега Description не должна превышать 300 символов, рекомендуемая длина: 160-180 символов..
        /// </summary>
        public static string MetatagDescriptionRecommendations {
            get {
                return ResourceManager.GetString("MetatagDescriptionRecommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метатег Keywords.
        /// </summary>
        public static string MetatagKeywords {
            get {
                return ResourceManager.GetString("MetatagKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Это поле не обязательно. Используется как памятка о том, какие ключевые слова нужно продвигать..
        /// </summary>
        public static string MetatagKeywordsRecommendations {
            get {
                return ResourceManager.GetString("MetatagKeywordsRecommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метатеги.
        /// </summary>
        public static string Metatags {
            get {
                return ResourceManager.GetString("Metatags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метатег Title.
        /// </summary>
        public static string MetatagTitle {
            get {
                return ResourceManager.GetString("MetatagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина метатега Title не должна превышать 90 символов, рекомендуемая длина: 60-70 символов..
        /// </summary>
        public static string MetatagTitleRecommendations {
            get {
                return ResourceManager.GetString("MetatagTitleRecommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модель.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название для URL.
        /// </summary>
        public static string NameForUrl {
            get {
                return ResourceManager.GetString("NameForUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ООО &quot;ОмЭнерго&quot;.
        /// </summary>
        public static string OOO_OmEnergo {
            get {
                return ResourceManager.GetString("OOO_OmEnergo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата и доставка.
        /// </summary>
        public static string PaymentAndDelivery {
            get {
                return ResourceManager.GetString("PaymentAndDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы работаем только с юридическими лицами по безналичному расчету.
        ///Условия оплаты - 100% предоплата.
        ///Для постоянных клиентов возможна частичная отсрочка платежа..
        /// </summary>
        public static string PaymentDescription {
            get {
                return ResourceManager.GetString("PaymentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер телефона.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фото.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пикселей.
        /// </summary>
        public static string Pixels {
            get {
                return ResourceManager.GetString("Pixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, заполните поле.
        /// </summary>
        public static string PleaseFillInTheField {
            get {
                return ResourceManager.GetString("PleaseFillInTheField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, выберите файл.
        /// </summary>
        public static string PleaseSelectAFile {
            get {
                return ResourceManager.GetString("PleaseSelectAFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продукт.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свойства модели продукта.
        /// </summary>
        public static string ProductModelProperties {
            get {
                return ResourceManager.GetString("ProductModelProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свойства продукта.
        /// </summary>
        public static string ProductProperties {
            get {
                return ResourceManager.GetString("ProductProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свойства.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свойства должны быть разделены точками с запятой, например &quot;Длина;Ширина;Высота&quot;.
        /// </summary>
        public static string PropertiesMustBeSeparatedBySemicolons {
            get {
                return ResourceManager.GetString("PropertiesMustBeSeparatedBySemicolons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По запросу ничего не найдено.
        /// </summary>
        public static string RequestReturnedNoResults {
            get {
                return ResourceManager.GetString("RequestReturnedNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Секция.
        /// </summary>
        public static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Секции.
        /// </summary>
        public static string Sections {
            get {
                return ResourceManager.GetString("Sections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порядковый номер.
        /// </summary>
        public static string SequenceNumber {
            get {
                return ResourceManager.GetString("SequenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подсекция.
        /// </summary>
        public static string Subsection {
            get {
                return ResourceManager.GetString("Subsection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такое название для URL уже существует.
        /// </summary>
        public static string SuchNameForUrlAlreadyExists {
            get {
                return ResourceManager.GetString("SuchNameForUrlAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введённые данные неверны.
        /// </summary>
        public static string TheEnteredDataIsIncorrect {
            get {
                return ResourceManager.GetString("TheEnteredDataIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение некорректно и не может быть обновлено.
        ///Таблица {{tableName}}, Строка: {{rowNumber}}
        ///Свойство: {{propertyName}}, Значение: {{propertyValue}}.
        /// </summary>
        public static string TheValueIsInvalidAndCannotBeUpdated {
            get {
                return ResourceManager.GetString("TheValueIsInvalidAndCannotBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string ToLogIn {
            get {
                return ResourceManager.GetString("ToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат загружаемого файла не поддерживается.
        ///Поддерживаемые форматы документов: {{supportedDocumentExtensions}}. 
        ///Поддерживаемые форматы изображений: {{supportedImageExtensions}}..
        /// </summary>
        public static string UploadFileFormatIsNotSupported {
            get {
                return ResourceManager.GetString("UploadFileFormatIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допустимый формат нецелых чисел: 1234.56 или 1234,56.
        /// </summary>
        public static string ValidNonIntegerFormat {
            get {
                return ResourceManager.GetString("ValidNonIntegerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to изменена.
        /// </summary>
        public static string WasChanged_f {
            get {
                return ResourceManager.GetString("WasChanged_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to изменён.
        /// </summary>
        public static string WasChanged_m {
            get {
                return ResourceManager.GetString("WasChanged_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to создана.
        /// </summary>
        public static string WasCreated_f {
            get {
                return ResourceManager.GetString("WasCreated_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to создан.
        /// </summary>
        public static string WasCreated_m {
            get {
                return ResourceManager.GetString("WasCreated_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to удалена.
        /// </summary>
        public static string WasDeleted_f {
            get {
                return ResourceManager.GetString("WasDeleted_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to удалён.
        /// </summary>
        public static string WasDeleted_m {
            get {
                return ResourceManager.GetString("WasDeleted_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время работы:
        ///Технические специалисты: 9:00-17:00;
        ///Выписка накладных: 9:30-16:30..
        /// </summary>
        public static string WorkingHours {
            get {
                return ResourceManager.GetString("WorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильный email.
        /// </summary>
        public static string WrongEmail {
            get {
                return ResourceManager.GetString("WrongEmail", resourceCulture);
            }
        }
    }
}
